### ISSUE TITLE
problem selecting file on macOS app 

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/select-multiple-data-split#1]
**on startup**
![screen shot 2018-09-10 at 8 49 43 am 1](https://user-images.githubusercontent.com/4806884/45298547-d4bda700-b4d6-11e8-964e-e21dce4d6f55.png)

**selecting a file**
![screen shot 2018-09-10 at 8 52 02 am](https://user-images.githubusercontent.com/4806884/45298560-de470f00-b4d6-11e8-86ea-d679cc321cd0.png)

**after selecting a file**
![screen shot 2018-09-10 at 8 52 06 am](https://user-images.githubusercontent.com/4806884/45298574-edc65800-b4d6-11e8-83f7-443eef7c3845.png)

**Comment by danbjoseph** [comment]
![screen shot 2018-09-10 at 9 16 40 am](https://user-images.githubusercontent.com/4806884/45299661-46e3bb00-b4da-11e8-958a-6299723ff61c.png)

**Comment by rajsingh8220** [comment]
Would you please test one more time:
Inside project Directory, Run:
```
npm install
npm run electron
```
Install Packager
```
# This module requires Node.js 4.0 or higher to run
# for use in npm scripts
npm install electron-packager --save-dev

# for use from cli
npm install electron-packager -g
```
Generate App (macOS)
```
electron-packager . --overwrite --platform=darwin --arch=x64 --icon=img/logo.icns --prune=true --out=<path where you wanna generate the package>
```
